### ISSUE TITLE
Request to join team

### ISSUE THREAD

**Issue by tylanmm** [BYUCS452F2021/Date-Night-Planner#1]
I think that this sounds like a really cool project idea! My wife and I are constantly finding ourselves in a similar situation, so I would be personally invested in the success of this project. Primarily because of the influence of the Church in this area, I agree that Provo is an ideal place to start because there are already so many businesses and locations that are dedicated to the purpose of giving couples a place to go on dates. I think that the market is wide-open for something a bit more targeted towards dates than something like Groupon is.

What I would contribute to the team would be general product organization and front-end web development. I also have experience working with back-end servers, using Node.js, Scala, and Java. My varied experience makes me particularly well-suited to help across the board, if not taking primary ownership, then at least providing the role of support across the entire development process of the app.

**Business:** the two primary ways I see money being made from this would be 1) we negotiate with businesses to take a portion of the revenue that comes from our users, and 2) advertisers pay for preferential viewership in the application.
**Operations:** regarding dynamically updating the app to include new businesses and activities, I think that this could be offloaded to the users to a certain degree. Think of Google Maps and how they reward users for answering questions and writing reviews; I think a similar system could be adopted, as to incentive users to provide new activities.
**Legal:** as stated, we would need to have contracts to give to businesses based on the type of business that they want to engage in. Furthermore, we would probably need a user agreement so that users are aware that the information that they impart to us voluntarily becomes company property (and that they aren't entitled to monetary reimbursement for their voluntary contributions).
**Technical:** I definitely think that a web application would likely be the easiest to get set up initially, though a mobile app would almost certainly be more useful to users.
**Social:** this idea has the potential to be something of a social network as users contribute activity ideas, and as was mentioned, as users group up to go on these dates.

I anxiously await your response, and hopefully I'll get to work with the team!

**Comment by TraceHale24** [comment]
Hey Tylan we would love to have you onboard with us!
