### ISSUE TITLE
Request to join team

### ISSUE THREAD

**Issue by rhinck** [BYUCS452F2021/Date-Night-Planner#3]
This project sounds like fun, especially because I was having a conversation about this exact topic yesterday with my wife. As mentioned by others, it would probably be easier to get traction in Provo. It would actually be really cool if we officially released it on the App Store and Google Play Store at the end of the semester. Maybe the app could have ideas submitted by users as well as maybe sponsored activities where couples can get a discount if they opt to do a paid activity.

You can check out some of my projects on the README on my [GitHub profile](https://github.com/rhinck). I'm a full-stack developer and I have experience with Flutter, React, Vue, Flask, Fast API, MongoDB, Express (Node), and more. I also have experience with Stripe, Retool, Firebase, in-app purchases, push notifications, etc. I can do whatever role the team prefers, but I would also love to actively participate in the database schema design because I feel like that's where I need to improve the most haha.

**Business**: Making partnerships with businesses for sponsored activities would bring in decent money. We could just take a cut off the top of the profit.
**Operations**: We could initially populate the app with some of our ideas, find some businesses to partner with to get the sponsored activities, and then allow community submissions from users that we could filter with an admin panel or something like that.
**Legal**: We need to make sure that we have good terms of service and privacy policy. The contracts we enter in with businesses should probably be vetted by a lawyer first.
**Technical**: A web application would be easiest to start with ie. Vue, but with a framework like Flutter we could potentially release it to all 3 platforms at once. Retool is an awesome low-code tool that I use at my startup to build out internal tools extremely quickly.
**Social**: It'd be awesome to potentially allow couples to find other couples to do group dates with. That has been a struggle for my wife and I lol.

Hope to be able to work with you and the team!

**Comment by Cbain10** [comment]
This is a great idea and addresses a problem I often have with my wife. We could definitely use a tool like this to make the most out of our time. It would be cool if we could get it released and used by real couples towards the end of the semester. 

I too am a full-stack developer and have experience with React, SwiftUI and Vue. I have experience creating mobile apps in for both Android and iOS. I also believe that I would be a valuable asset designing the UI and front-end if we decide to put any focus on that. 

Business: Ads are on option, in addition to taking a percentage of the profits for sponsored activities. 
Operations: I think implementing community activities and ratings could be very powerful. Even utilizing an API for something like trip advisor would be very effective.
Legal: Having a solid/secure privacy policy is a priority, especially when implementing sponsored events from external businesses.
Technical: I think just out of convenience it would be best to start with a mobile app. As small of a task as it is, I think it would be a pain point to get out your computer to figure out date night. React Native would be a good option, along with Flutter if we are wanting to develop for both Android and iOS (if not then SwiftUI would likely appeal to the largest group in Provo).
Social: Would definitely be cool to easily send a message to another couple with the night plans, trying to make it a group date.

Would love to join the team!

**Comment by TraceHale24** [comment]
Hey Robert we would love to have you onboard with us!
