### ISSUE TITLE
Request to join team

### ISSUE THREAD

**Issue by Cbain10** [BYUCS452F2021/Date-Night-Planner#4]
This is a great idea and addresses a problem I often have with my wife. We could definitely use a tool like this to make the most out of our time. It would be cool if we could get it released and used by real couples towards the end of the semester.

I too am a full-stack developer and have experience with React, SwiftUI and Vue. I have experience creating mobile apps in for both Android and iOS. I also believe that I would be a valuable asset designing the UI and front-end if we decide to put any focus on that.

Business: Ads are on option, in addition to taking a percentage of the profits for sponsored activities.
Operations: I think implementing community activities and ratings could be very powerful. Even utilizing an API for something like trip advisor would be very effective.
Legal: Having a solid/secure privacy policy is a priority, especially when implementing sponsored events from external businesses.
Technical: I think just out of convenience it would be best to start with a mobile app. As small of a task as it is, I think it would be a pain point to get out your computer to figure out date night. React Native would be a good option, along with Flutter if we are wanting to develop for both Android and iOS (if not then SwiftUI would likely appeal to the largest group in Provo).
Social: Would definitely be cool to easily send a message to another couple with the night plans, trying to make it a group date.

Would love to join the team!

**Comment by TraceHale24** [comment]
Hey Christian we would love to have you onboard with us!

**Comment by Cbain10** [comment]
Awesome! Looking forward to it!
