### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by wademcmillan** [BYUCS452F2021/Date-Night-Planner#5]
I think this idea is awesome because of how many times I wished someone would just make the decision for what to do. I love the idea of having an app that takes in parameters and assigns the nightly activites. 

What I would contribute to the team would be a relatively free schedule where I can put in plenty of work, the general knowledge gained through the CS classes as well as experience working to keep a CRM server working and improving the front end and access to the databases.

Business: I see this making money mostly through adds.
Operations: I see us maintaining and developing it and then having users like or add comments or new activities to improve a ranking system. 
Legal: I think that this is something that can be dealt with if needs be. If it becomes a viable business you would own the vast majority. We would have to have a waiver for users if we use their personal information.
Technical: I'm open to a web app for ease or a mobile app for greater market appeal. 
Social: I think that this could have a great impact on peoples social lives.

It was good talking to you earlier over slack and I hope we can work together soon.

**Comment by TraceHale24** [comment]
Hey Wade we would love to have you on board with us!
